import os

BOT_TOKEN = os.getenv("BOT_TOKEN", "NzA3MTM5ODA4MDAyMzEwMTk0.GhZKj7.L1NLL-wHPEF0DQbCkWWBABCPY9tjLlWA4WiVzM")

DEFAULT_PREFIX = os.getenv("DEFAULT_PREFIX", ">")

DEFAULT_EMOJI = os.getenv("DEFAULT_EMOJI", ":game_die:")

SYSTEM_NAME = os.getenv("SYSTEM_NAME", "NEW SYSTEM")

SYSTEM_ABV = os.getenv("SYSTEM_ABV", "NEWSYS")
